using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;

namespace mantis_auto
{
    [TestFixture]
    class AddProjectTests : AuthTestBase
    {
        [Test]
        public void AddProjectTest()
        {
            AccountData account = new AccountData()
            {
                Name = "administrator",
                Password = "root"
            };
            //app.Login.LoginToTheSystem(account);
            app.LeftMenu.OpenManagement();
            app.Project.OpenManageProjects();
            ProjectData prj;
            List<ProjectData> oldProjects = app.Project.GetAllFromScreen();
            do
            {
                prj = new ProjectData("AutoGenerated" + NumberGenerator(5000));

            } while (ProjectData.GetDataFromDB().Contains(prj));

            app.Project.Create(prj);
           
            oldProjects.Add(prj);
            app.LeftMenu.OpenManagement();
            app.Project.OpenManageProjects();
            
            List<ProjectData> newProjects = app.Project.GetAllFromScreen();
            oldProjects.Sort();
           
            newProjects.Sort();
            Assert.AreEqual(oldProjects, newProjects);

        }

        private int NumberGenerator(int max)
        {
            Random random = new Random();
            return random.Next(0, max);
        }
    }
}
